#!/usr/bin/env python3
"""AES Phase 3 artifact-freshness pilot: deterministic generate/validate tool.

This script is scoped ONLY to the pilot fixture pair under
docs/autonomous_execution/pilot_fixtures/. It is not a general-purpose
generator and must not be pointed at real Knowledge Bundles.

Modes:
  generate  Regenerate the derived fixture from the source fixture and stamp
            a manifest header recording generated_from_revision (the source
            file's content hash) and generated_at.
  check     Recompute the source content hash and compare it against the
            hash recorded in the derived fixture's manifest header. Exits
            non-zero and prints "STALE" if they differ, prints "CURRENT" if
            they match.

Usage:
  python3 scripts/pilot_generate_artifact_fixture.py generate
  python3 scripts/pilot_generate_artifact_fixture.py check
"""

from __future__ import annotations

import datetime
import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = REPO_ROOT / "docs/autonomous_execution/pilot_fixtures/aes_artifact_pilot_source.md"
DERIVED_PATH = REPO_ROOT / "docs/autonomous_execution/pilot_fixtures/aes_artifact_pilot_derived.md"

FACT_LINE_PATTERN = re.compile(r"^-\s*([a-zA-Z_]+):\s*(.+)$")
HASH_PATTERN = re.compile(r"generated_from_revision:\s*(sha256:[0-9a-f]{64})")


def source_content_hash() -> str:
    digest = hashlib.sha256(SOURCE_PATH.read_bytes())
    return f"sha256:{digest.hexdigest()}"


def parse_facts(text: str) -> list[tuple[str, str]]:
    facts = []
    for line in text.splitlines():
        match = FACT_LINE_PATTERN.match(line.strip())
        if match:
            facts.append((match.group(1), match.group(2)))
    return facts


def generate() -> None:
    source_text = SOURCE_PATH.read_text(encoding="utf-8")
    facts = parse_facts(source_text)
    content_hash = source_content_hash()
    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# AES Artifact Pilot — Derived Fixture (pilot fixture, not real product content)",
        "",
        "Status: pilot fixture for `docs/pilots/AES_ARTIFACT_PILOT.md`. Generated by",
        "`scripts/pilot_generate_artifact_fixture.py generate` from",
        "`docs/autonomous_execution/pilot_fixtures/aes_artifact_pilot_source.md`.",
        "Do not hand-edit this file; re-run the generator instead.",
        "",
        "## Manifest",
        "",
        f"- source_path: docs/autonomous_execution/pilot_fixtures/aes_artifact_pilot_source.md",
        f"- generated_from_revision: {content_hash}",
        f"- generated_at: {generated_at}",
        "",
        "## Generated Table",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    for key, value in facts:
        lines.append(f"| {key} | {value} |")
    lines.append("")

    DERIVED_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"GENERATED {DERIVED_PATH.relative_to(REPO_ROOT)}")
    print(f"generated_from_revision: {content_hash}")


def check() -> int:
    if not DERIVED_PATH.exists():
        print("FAIL: derived fixture does not exist; run generate first")
        return 2

    derived_text = DERIVED_PATH.read_text(encoding="utf-8")
    match = HASH_PATTERN.search(derived_text)
    if not match:
        print("FAIL: derived fixture missing generated_from_revision in manifest")
        return 2

    recorded_hash = match.group(1)
    current_hash = source_content_hash()

    print(f"source current content_hash:      {current_hash}")
    print(f"derived generated_from_revision:  {recorded_hash}")

    if recorded_hash == current_hash:
        print("CURRENT: derived fixture matches current source content")
        return 0

    print("STALE: source content has changed since the derived fixture was generated")
    return 1


def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] not in {"generate", "check"}:
        print(__doc__)
        return 2
    if sys.argv[1] == "generate":
        generate()
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
